services:
  flask_app:
    container_name: flask_app
    image: gerenuk/flask_live_app:latest
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - DB_URL
      - OPENAI_API_KEY
      - FLASK_ENV
    depends_on:
      - flask_db
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: ./app
  flask_db:
    container_name: flask_db
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
    
