name: Docker Build

on:
  push:
    branches: [ main, video ]
    paths:
      - 'backend/**'
      - '.github/workflows/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push content moderator service
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend/content_moderator"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/content_moderator_app:latest
      -
        name: Build and push video snapshotter service
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend/snapshotter"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/video_snapshotter_app:latest
